/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#include <gtest/gtest.h>
#include "app/app.hpp"

TEST(TestServer, when_set_Port_Message_Should_Works)
{
    EXPECT_EQ(1000, 1000);
}

TEST(TestServer2, when_set_Port_Message_Should_Works)
{
    EXPECT_EQ(10, 1000);
}

/*
int main() {
    Leaf::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
*/
