name: Build & Push cmake_with_conan container

on:
  push:
    branches: [ main ]
    paths:
      - "docker/cmake_with_conan/**"
  pull_request:
    branches: [ main ]
    paths:
      - "docker/cmake_with_conan/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Build container
        run: |
          docker build -t ghcr.io/loic-lopez/cmake_with_conan:${{ steps.gitversion.outputs.semVer }} docker/cmake_with_conan

  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to ghcr.io registry
        run: |
          echo ${{ secrets.PUSH_CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Tag container
        run: |
          docker build -t ghcr.io/loic-lopez/cmake_with_conan:${{ needs.build.outputs.semVer }} docker/cmake_with_conan

      - name: Push container
        run: |
          docker push ghcr.io/loic-lopez/cmake_with_conan:${{ needs.build.outputs.semVer }}
