name: Build & Push cmake_with_conan container

on:
  push:
    branches: [ main ]
    paths:
      - "docker/cmake_with_conan/**"
  pull_request:
    branches: [ main ]
    paths:
      - "docker/cmake_with_conan/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.prefixed_semver.outputs.semVer }}
      branchName: ${{ steps.gitversion.outputs.branchName }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Add prefix to semVer calculated by GitVersion
        id: prefixed_semver
        run: echo '::set-output name=semVer::v${{ steps.gitversion.outputs.semVer }}'

      - name: Build ghcr.io/loic-lopez/cmake_with_conan:${{ steps.prefixed_semver.outputs.semVer }} container
        run: docker build -t ghcr.io/loic-lopez/cmake_with_conan:${{ steps.prefixed_semver.outputs.semVer }} docker/cmake_with_conan

  push:
    runs-on: ubuntu-latest
    needs: build
    if: contains(needs.build.outputs.branchName, 'main')
    steps:
      - name: Login to ghcr.io registry
        run: echo ${{ secrets.PUSH_CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Tag latest container
        run: docker tag ghcr.io/loic-lopez/cmake_with_conan:${{ needs.build.outputs.semVer }} ghcr.io/loic-lopez/cmake_with_conan:latest

      - name: Push ghcr.io/loic-lopez/cmake_with_conan:${{ needs.build.outputs.semVer }} container
        run: docker push ghcr.io/loic-lopez/cmake_with_conan:${{ needs.build.outputs.semVer }}

      - name: Push ghcr.io/loic-lopez/cmake_with_conan:latest container
        run: docker push ghcr.io/loic-lopez/cmake_with_conan:latest
