name: Build & Push sonar_cloud_scanner container

on:
  push:
    branches: [ main ]
    paths:
      - "docker/sonar_cloud_scanner/**"
  pull_request:
    branches: [ main ]
    paths:
      - "docker/sonar_cloud_scanner/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.prefixed_semver.outputs.semVer }}
      branchName: ${{ steps.gitversion.outputs.branchName }}
      artifactName: ${{ steps.image_artifact.outputs.name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Add prefix to semVer calculated by GitVersion
        id: prefixed_semver
        run: echo '::set-output name=semVer::v${{ steps.gitversion.outputs.semVer }}'

      - name: Build ghcr.io/loic-lopez/sonar_cloud_scanner:${{ steps.prefixed_semver.outputs.semVer }} container
        run: docker build -t ghcr.io/loic-lopez/sonar_cloud_scanner:${{ steps.prefixed_semver.outputs.semVer }} docker/sonar_cloud_scanner

      - name: Set name of exported tar to github actions artifacts
        id: image_artifact
        run: echo '::set-output name=name::sonar_cloud_scanner_${{ steps.prefixed_semver.outputs.semVer }}_image.tar'

      - name: Prepare export ghcr.io/loic-lopez/sonar_cloud_scanner:${{ steps.prefixed_semver.outputs.semVer }} to github actions artifacts
        run: |
          mkdir -p sonar_cloud_scanner/
          docker save \
            ghcr.io/loic-lopez/sonar_cloud_scanner:${{ steps.prefixed_semver.outputs.semVer }} > \
            sonar_cloud_scanner/${{ steps.image_artifact.outputs.name }}

      - uses: actions/upload-artifact@v2
        with:
          name: sonar_cloud_scanner_${{ steps.prefixed_semver.outputs.semVer }}
          path: sonar_cloud_scanner/${{ steps.image_artifact.outputs.name }}

  push:
    runs-on: ubuntu-latest
    needs: build
    if: contains(needs.build.outputs.branchName, 'main')
    steps:
      - name: Download sonar_cloud_scanner:${{ needs.build.outputs.semVer }} Docker image (Artifact)
        uses: actions/download-artifact@v2
        with:
          name: sonar_cloud_scanner_${{ needs.build.outputs.semVer }}
          path: sonar_cloud_scanner/

      - name: Load sonar_cloud_scanner:${{ needs.build.outputs.semVer }} Docker image
        run: docker load < sonar_cloud_scanner/${{ needs.build.outputs.artifactName }}

      - name: Tag latest container
        run: docker tag ghcr.io/loic-lopez/sonar_cloud_scanner:${{ needs.build.outputs.semVer }} ghcr.io/loic-lopez/sonar_cloud_scanner:latest

      - name: Login to ghcr.io registry
        run: echo ${{ secrets.PUSH_CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push ghcr.io/loic-lopez/sonar_cloud_scanner:${{ needs.build.outputs.semVer }} container
        run: docker push ghcr.io/loic-lopez/sonar_cloud_scanner:${{ needs.build.outputs.semVer }}

      - name: Push ghcr.io/loic-lopez/sonar_cloud_scanner:latest container
        run: docker push ghcr.io/loic-lopez/sonar_cloud_scanner:latest
